import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
import { extension } from './extension-host.mjs';
import { extractExamples, mergeBlocks } from './markdown.mjs';
import { fixtures } from './fragments.mjs';
import { SUPPORTED_EFFECT_VERSION } from '../hooks/effect-version.mjs';
import { fileURLToPath } from 'node:url';
const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const dependencies = JSON.parse(fs.readFileSync(path.join(here, 'package.json'), 'utf8')).devDependencies;
for (const name of Object.keys(dependencies)) {
  if (!/^\d+\.\d+\.\d+(?:-[a-z0-9.]+)?$/.test(dependencies[name])) throw new Error(`Dependency must be exact: ${name}`);
  if (name === 'effect' || name.startsWith('@effect/')) {
    if (dependencies[name] !== SUPPORTED_EFFECT_VERSION) throw new Error(`Unpinned or mismatched dependency: ${name}`);
  }
  const installed = JSON.parse(fs.readFileSync(path.join(here, 'node_modules', name, 'package.json'), 'utf8')).version;
  if (installed !== dependencies[name]) throw new Error(`Installed version mismatch: ${name}`);
}
const generated = path.join(here, 'generated');
fs.rmSync(generated, { recursive: true, force: true });
fs.mkdirSync(generated, { recursive: true });
const skill = path.join(root, 'skills/effect-ts');
const files = fs.readdirSync(skill, { recursive: true }).filter(x => x.endsWith('.md')).sort().map(x => path.join(skill, x));
const groups = new Map();
const inventory = [];
const usedFixtures = new Set();
const groupOwners = new Map();
const grouped = { 'cli-tasks': 4, 'config-basic': 2, 'testing-events': 3 };
const extensions = new Map();
for (const file of files) {
  const source = fs.readFileSync(file, 'utf8');
  let count = 0;
  for (const { kind, label: id, code, line, extension } of extractExamples(source, file)) {
    count++;
    const name = kind === 'check' ? id : `fragment-${path.basename(file, '.md')}-${count}`;
    inventory.push({ file: path.relative(root, file), block: count, line, kind,
      module: name, reason: kind === 'fragment' ? id : undefined });
    extensions.set(name, extension);
    if (kind === 'check') {
      if (groups.has(id) && (!grouped[id] || groupOwners.get(id) !== file)) throw new Error(`Duplicate example ID: ${id}`);
      groupOwners.set(id, file);
      groups.set(id, [...(groups.get(id) ?? []), code]);
    } else {
      const key = `${path.basename(file)}:${count}`;
      const fixture = fixtures[key];
      if (!fixture) throw new Error(`Missing typed fixture: ${key}`);
      usedFixtures.add(key);
      let body = code;
      let prelude = fixture.prelude + '\n';
      if (fixture.generator) {
        body = body.replace(/^import [^\n]+\n/gm, line => { prelude += line; return ''; });
        body = `const example = Effect.gen(function* () {\n${body}\n});`;
      }
      groups.set(`fragment-${path.basename(file, '.md')}-${count}`, [prelude, body]);
    }
  }
}
for (const key of Object.keys(fixtures)) {
  if (!usedFixtures.has(key)) throw new Error(`Stale fragment fixture: ${key}`);
}
for (const [id, count] of Object.entries(grouped)) {
  if (groups.get(id)?.length !== count) throw new Error(`Expected ${count} blocks for ${id}`);
}
// Runtime tests use the CLI definitions without the Bun entry point.
if (groups.has('cli-repository')) throw new Error('cli-repository is reserved for the extracted CLI runtime module');
groups.set('cli-repository', groups.get('cli-tasks').slice(0, 3));
for (const [name, blocks] of groups) {
  fs.writeFileSync(path.join(generated, `${name}.${extensions.get(name) ?? 'ts'}`), mergeBlocks(blocks));
}
// Compile the exact text delivered by the registered tool, including its version gate.
const app = extension();
await app.events.session_start({}, { cwd: here, ui: { setStatus() {}, notify() {} } });
for (const type of ['service', 'schema', 'error', 'test']) {
  const result = await app.tools.effect_scaffold.execute('validation', { type, name: 'Example' });
  const name = `generate${type[0].toUpperCase() + type.slice(1)}Scaffold`;
  const exports = type === 'error' ? 'export { ExampleNotFoundError, ExampleValidationError, ExampleError }' : 'export {}';
  fs.writeFileSync(path.join(generated, `${name}.ts`), result.content[0].text + `\n${exports}\n`);
}
const summary = [...new Set(inventory.map(x => x.file))].map(file => {
  const entries = inventory.filter(x => x.file === file);
  return `| [${path.basename(file)}](../${file}) | ${entries.filter(x => x.kind === 'check').length} | ${entries.filter(x => x.kind === 'fragment').length} |`;
});
const coverage = `# Documentation coverage

Generated by \`npm --prefix validation run coverage:update\`. Validation rejects a stale report.

Every TypeScript fence in the skill and its references compiles. Complete examples use their published imports. Fragments receive the typed context in [fragments.mjs](fragments.mjs). Each exclusion below explains why the fragment is not run.

| Source | Complete or grouped blocks | Fragments with typed context |
| --- | ---: | ---: |
${summary.join('\n')}

## Fragment runtime exclusions

| Published block | Missing context or reason |
| --- | --- |
${inventory.filter(x => x.kind === 'fragment').map(x => `| [${path.basename(x.file)} #${x.block}](../${x.file}#L${x.line}) | ${x.reason.replaceAll('|', '\\|').replaceAll('<', '&lt;').replaceAll('>', '&gt;')} |`).join('\n')}

Runtime coverage and host limits are in [README.md](README.md). The generated inventory records each module's source line for compiler diagnostics.
`;
const coverageFile = path.join(here, 'coverage.md');
if (process.argv.includes('--update-coverage')) fs.writeFileSync(coverageFile, coverage);
else if (!fs.existsSync(coverageFile) || fs.readFileSync(coverageFile, 'utf8') !== coverage) {
  throw new Error('Coverage changed. Review the fences and run npm --prefix validation run coverage:update.');
}
fs.writeFileSync(path.join(generated, 'inventory.json'), JSON.stringify(inventory, null, 2));
fs.writeFileSync(path.join(generated, 'package.json'), JSON.stringify({type: 'module', version: '1.0.0'}));
const sourceFiles = fs.readdirSync(generated).filter(x => /\.tsx?$/.test(x)).map(x => path.join(generated, x));
const localTests = fs.readdirSync(here).filter(x => x.endsWith('.test.ts') || x === 'vitest.config.ts').map(x => path.join(here, x));
const program = ts.createProgram([...sourceFiles, ...localTests], {
  target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext,
  moduleResolution: ts.ModuleResolutionKind.Bundler, strict: true,
  exactOptionalPropertyTypes: true, noEmit: true, skipLibCheck: true,
  jsx: ts.JsxEmit.ReactJSX, resolveJsonModule: true, allowSyntheticDefaultImports: true, types: ['node'], typeRoots: [path.join(here, 'node_modules/@types')],
});
const diagnostics = ts.getPreEmitDiagnostics(program);
if (diagnostics.length) {
  console.error(ts.formatDiagnosticsWithColorAndContext(diagnostics, {
    getCanonicalFileName: x => x, getCurrentDirectory: () => here, getNewLine: () => '\n',
  }));
  process.exitCode = 1;
} else {
  console.log(`Checked ${inventory.length} Markdown blocks: ${inventory.filter(x => x.kind === "check").length} complete/grouped and ${inventory.filter(x => x.kind === "fragment").length} illustrative with typed fixtures, plus 4 generated scaffolds. Inventory: generated/inventory.json.`);
}
